/**
 * Caption types for delivery automation.
 * Cues can be generated by a future narration/script agent or supplied by the calling workflow.
 */

export interface CaptionCue {
  readonly startSecond: number;
  readonly endSecond: number;
  readonly text: string;
}

export interface CaptionOptions {
  readonly enabled: boolean;
  readonly burnIn: boolean;
  readonly language?: string;
}

export interface CaptionArtifact {
  readonly srtPath: string;
  readonly cueCount: number;
  readonly language?: string;
  readonly burnedIn: boolean;
}

export interface CaptionRenderInput {
  readonly projectId: string;
  readonly inputVideoPath: string;
  readonly outputVideoPath: string;
  readonly workDirectory: string;
  readonly cues: readonly CaptionCue[];
  readonly options: CaptionOptions;
}
